<a href="https://colab.research.google.com/github/WoobinSeo/machine-learning/blob/main/practice_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import pandas as pd

iris = pd.read_csv('https://raw.githubusercontent.com/jmnote/zdata/master/R/iris.csv')
iris.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [16]:
print(pd.unique(iris['Species']))

['setosa' 'versicolor' 'virginica']


In [19]:
iris_input = iris[['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width']].to_numpy()
iris_target = iris['Species'].to_numpy()

In [25]:
print(iris_input[:5])
print(iris_target[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
['setosa' 'setosa' 'setosa' 'setosa' 'setosa']


In [32]:
from sklearn.model_selection import train_test_split

train_input, test_input, train_target, test_target = train_test_split(
    iris_input, iris_target)

In [34]:
from sklearn.neighbors import KNeighborsClassifier
kn = KNeighborsClassifier()
kn.fit(train_input, train_target)
print(kn.score(train_input, train_target))
print(kn.score(test_input, test_target))

0.9910714285714286
0.9473684210526315


In [49]:
print(kn.predict(test_input[:5]))

import numpy as np

proba = kn.predict_proba(test_input[:5])
print(np.round(proba, decimals=4))

['virginica' 'virginica' 'virginica' 'virginica' 'virginica']
[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]


In [35]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

In [36]:
kn.fit(train_scaled, train_target)

print(kn.score(train_scaled, train_target))
print(kn.score(test_scaled, test_target))

0.9821428571428571
0.9210526315789473


In [39]:
import numpy as np

setosa_versicolor_indexes = (train_target == 'setosa') | (train_target == 'versicolor')
train_setosa_versicolor = train_scaled[setosa_versicolor_indexes]
target_setosa_versicolor = train_target[setosa_versicolor_indexes]

In [40]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(train_setosa_versicolor, target_setosa_versicolor)

LogisticRegression()

In [42]:
print(lr.predict(train_setosa_versicolor[:5]))
print(lr.classes_)
print(lr.predict_proba(train_setosa_versicolor[:5]))

['setosa' 'setosa' 'setosa' 'versicolor' 'versicolor']
['setosa' 'versicolor']
[[0.94659783 0.05340217]
 [0.94789593 0.05210407]
 [0.98306199 0.01693801]
 [0.02173356 0.97826644]
 [0.01961518 0.98038482]]


In [43]:
lr = LogisticRegression(C=20, max_iter=1000)
lr.fit(train_scaled, train_target)

print(lr.score(train_scaled, train_target))
print(lr.score(test_scaled, test_target))

1.0
0.8947368421052632


In [45]:
print(lr.predict(test_scaled[:5]))
proba = lr.predict_proba(test_scaled[:5])
print(lr.classes_)
print(np.round(proba, decimals=3))

['versicolor' 'setosa' 'virginica' 'versicolor' 'setosa']
['setosa' 'versicolor' 'virginica']
[[0.023 0.977 0.   ]
 [0.973 0.027 0.   ]
 [0.    0.128 0.872]
 [0.002 0.977 0.021]
 [0.999 0.001 0.   ]]


In [46]:
decision = lr.decision_function(test_scaled[:5])
print(np.round(decision, decimals=2))

[[  0.78   4.52  -5.3 ]
 [ 11.34   7.76 -19.1 ]
 [ -6.6    2.34   4.26]
 [ -2.82   3.33  -0.51]
 [ 14.44   6.96 -21.4 ]]


In [47]:
from scipy.special import softmax

proba = softmax(decision, axis=1)
print(np.round(proba, decimals=3))

[[0.023 0.977 0.   ]
 [0.973 0.027 0.   ]
 [0.    0.128 0.872]
 [0.002 0.977 0.021]
 [0.999 0.001 0.   ]]
